version: '3'

services:
  webapp:
    container_name: community-hack
    image: node:10
    networks:
      - frontend
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm rebuild node-sass && npm run dev"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      API_URL: http://10.162.110.117

networks:
  frontend:
